[tool.poetry]
name = "rabbitmq"
version = "0.1.0"
description = ""
authors = ["VictorHu93 <victor45663@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pika = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
